package MichaelRaineri;

public class VigenereCipher {

    public static void main(String args[]){
        String plainText;
        String key = "JXQQXP";
        String cipher = "MLWTZZXUEUWFUMTCIKPASLTGLSSMPE";
        char[] alphabet = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};

        String q2Cipher = "MLWTZZXUEUWFUMTCIKPASLTGLSSMPE";
        String q2Key = "TESSOFTHEDURBERVILLES";
        String q3cipher = "QCLUQDUFJXXIUKUJETWPULBGVKDTQWNTUIQPOVUHXAUVXUOTJTUVBLYWHUOIQKDWPXWPQJRGNVXUKPWWDIRAUKUTZDDPJHVBJKTQKNLTKTBCNUIECBJPDUOLQKSXJPHQVVBCMAEKOBXTUUAJLCJUAHNPIUXIOKHIQLRNBYXBBWHUAXBCFFBPAWDTBGCJUYKUUWUDZTXTOERGLQCFXCRQDIEXYCDTQJRVYEKHDEXJBGAKRBBHJTSQPBXHRBFCMOQWKPWKCYQNKTEKDWCJECBIXEBQOTCJUIBRXPTQONYGHSBECKEDQWJVXUEPMWJJBGUAMHBRTGTXFHLCHUBGKAJXFHVCHHFPPGMXFRQJQTKDCDUUKPVQDWEXBGQHINCJEKDWCUQVQTAVXUAXBEBEPJAGJHRTXPXYPDFPQSZDDPJXBRJTUTSTAABYQIUGQRLJCJYIZPAGUHYJCJUXXSFKIXBSCQCQHTRVQJITJUJQOTBRUSQPKNUEKTXPQSZDDPJECWRUFQOTWVIQKSKTEJETAUQDACXYQIETUQEABSRPJEQWNEQDAANKJICAJOUTRBKNOUUEAGIIBSCQXYJIQCJYQLJUCQATCQIXFCNQDIBCBKRBBENQFBBPWFJXXIRVQREDATUTIXPJJYKVCJUVXRNQVQAJYGQDAPOCYBRGNYXUKWRUQWFIJVYEKWJFSELANFXUTDDNTRBPCOECBCCUYDZTWUUTTXCJXYPEXQHMFUNHEHZPDUYDDPBKJKXIRQDYKLQKSXETFCIEYARIUTQDYTQSQXBGTUZTYVYEKDWJYIMPAGDJPWNCBCLHCVQBHTMVEXBGRPXYPPWIUHXH";
        String q3Key = "JCQQXP";
        String q3PlainText= "HAVETOLDTHATLIETHENNEVERMINDTHERESTAFTERALLTHEREAREFEWPURERTHINGSINNATURETHENANUNSULLIEDCOUNTRYMAIDANYCRUDENESSOFMANNERWHICHMAYOFFENDYOURMOREEDUCATEDSENSEATFIRSTWILLIAMSUREDISAPPEARUNDERTHEINFLUENCEORYOURCOMPANIONSHIPANDTUITIONSUCHTERRIBLESARCASMOFBLINDMAGNANIMITYBROUGHTHOMETOCLARETHESECONDARYPERCEPTIONTHATHEHADUTTERLYWRECKEDHISCAREERBYTHISMARRIAGEWHICHHADNOTBEENAMONGHISEARLYTHOUGHTSAFTERTHEDISCLOSURETRUEONHISOWNACCOUNTHECAREDVERYLITTLEABOUTHISCAREERBUTHEHADWISHEDTOMAKEITATLEASTARESPECTABLEONEONACCOUNTOFHISPARENTSANDBROTHERSANDNOWASHELOOKEDINTOTHECANDLEITSFLAMEDUMBLYEXPRESSEDTOHIMTHATITWASMADETOSHINEONSENSIBLEPEOPLEANDTHATITABHORREDLIGHTINGTHEFACEOFADUPEANDAFAILUREWHENHISAGITATIONHADCOOLEDHEWOULDBEATMOMENTSINCENSEDWITHHISPOORWIFEFORCAUSINGASITUATIONINWHICHHEWASOBLIGEDTOPRACTISEDECEPTIONONHISPARENTSHEALMOSTTALKEDTOHERINHISANGERAS";
        String q4Cipher = "GBDFGSUNRTMVCRDKSFZRGVMCDMOHSGDOAHCFRCGDXFCNNCFCHKKJQDQDHYNMKVCSKDSDQQDQJMCERJSGDENCGDNMRONCYDCTCOQNLGQDRLBXSGRHAEZBRXESGRFZSDEKTSEVWCHMTCGZSGQDCHFCTQAVWFOQRBDMBRBGZCCJTRDQJMCMBCOZRFNCAXGQDXCVBZOORJQDCNPZHMHYNMSURRQHINQAQVWJSGRHKHMTNQDCGRKKSUNENFONFZMGXBKNFNQNTAMSGDZFGHBUFZRURAXDZEUXHMGQDDURWHMFNCSGHFCHLDBOSGDLNZQRRCSKHAPNMSUNKZRUNRNEUNQDXRBVGDENHSQRBSDCYRJDBEHRSZYBZMCBWGHROANVRNWCGZVASGDLFZKJRMKZSRANMRHWCZXFFGDMVCVZRDDHSDQJQJRBVDNEGQDCZVAXODBYKDVUXVDQRJKRNBDSNEQXNQRBWSGDSRQRSFDMCZLNUDMVWFZEGNQSGRRQDMTJFDLRWSGDNACGDERLOTYBHUDFYDDBUNRDBFCZRHMNCSNSAZFLRWSRSUXTFGGQDXVRADSNBOZQNSOSNGRJQSGRFNQCFMHRBBDQRDQWNSDQCGDRCJRLNQRBBZGLGHMUNQQDZJQJROANJDARMSNFHKKZOUDRALCGDKRJOHMTBNEGRAGDZECZRRUNVZKXNCKDNWHMFBWGHRNALGDELNMSRWSDCCJTRDFCGDNPLZRHBWZKKVCSKDYJTFGHYNMVURBGGRARNTYBDDLRMSNQVMDSGRUZTFUXEZVBVZMHALNLONWXVHGQSGDZJMRGRUNUDFJMCGNBVNMSANLZYUNS";
        String q4Key4 = "NZZZ";
        String q4Key5 = "ZNJZZ";
        String q4Key6 = "NZZNNZ";
        String q4PlainText = "HOUGHTHESUNITSELFWASHIDDENBYTHEBRIDGETHEYSTOODSTILLWHEREUPONLITTLEFURREDANDFEATHEREDHEADSPOPPEDUPFROMTHESMOOTHSURFACEOFTHEWATERBUTFINDINGTHATTHEDISTURBINGPRESENCESHADPAUSEDANDNOTPASSEDBYTHEYDISAPPEAREDAGAINUPONTHISRIVERBRINKTHEYLINGEREDTILLTHEFOGBEGANTOCLOSEROUNDTHEMWHICHWASVERYEARLYINTHEEVENINGATTHISTIMEOFTHEYEARSETTLINGONTHELASHESOFHEREYESWHEREITRESTEDLIKECRYSTALSANDONHISBROWSANDHAIRTHEYWALKEDLATERONSUNDAYSWHENITWASQUITEDARKSOMEOFTHEDAIRYPEOPLEWHOWEREALSOOUTOFDOORSONTHEFIRSTSUNDAYEVENINGAFTERTHEIRENGAGEMENTHEARDHERIMPULSIVESPEECHESECSTASIZEDTOFRAGMENTSTHOUGHTHEYWERETOOFAROFFTOHEARTHEWORDSDISCOURSEDNOTEDTHESPASMODICCATCHINHERREMARKSBROKENINTOSYLLABLESBYTHELEAPINGSOFHERHEARTASSHEWALKEDLEANINGONHISARMHERCONTENTEDPAUSESTHEOCCASIONALLITTLELAUGHUPONWHICHHERSOULSEEMEDTORIDETHELAUGHOFAWOMANINCOMPANYWITHTHEMANSHELOVESANDHASWONFROMALLOT";


//        decrypt(cipher,q2Key);
//        System.out.println();
//        decrypt(q3cipher, q3Key);
//        System.out.println();
//        thirtyChar(q3PlainText);
//        System.out.println();
//        decrypt(q4Cipher, q4Key4);
//        System.out.println();
//        decrypt(q4Cipher, q4Key5);
//        System.out.println();
//        decrypt(q4Cipher, q4Key6);
//        thirtyChar(q4PlainText);

    }







    // PlainText^i = Decription^key(Cipher^i) = (cipher^i - Key^i + 26) mod 26
    public static void decrypt( String text, String key){
        String result= "";

        for (int i = 0, j = 0 ; i< text.length(); i++){

            // check if the char is between A-Z
            char b = text.charAt(i);
            //make sure the characters are in the alphabet
            if (b < 'A' || b > 'Z') continue;

            result += (char) (((b - key.charAt(j) + 26) % 26) + 'A');
            j = ++j %key.length();
        }
        System.out.println(result);
    }


    public static void getThirtyChar(String text){
        for (int i = 0 ; i < 30; i++){
            text.charAt(i);
            System.out.print(text.charAt(i));
        }

    }

}

